# Generated by Django 4.2.28 on 2026-03-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
    ]
