# Generated by Django 4.2.28 on 2026-02-28 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('flight', 'Flight Booking'), ('private_jet', 'Private Jet Charter'), ('visa', 'Visa Service'), ('hotel', 'Hotel Reservation'), ('transport', 'Transport Service'), ('passport', 'Passport Renewal'), ('protocol', 'Airport Protocol')], max_length=50)),
                ('reference_code', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=30)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('external_service_id', models.CharField(blank=True, max_length=100, null=True)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
