# Generated by Django 4.2.28 on 2026-03-20 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_bookinglock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='service_type',
            field=models.CharField(choices=[('flight', 'Flight Booking'), ('private_jet', 'Private Jet Charter'), ('visa', 'Visa Service'), ('hotel', 'Hotel Reservation'), ('transport', 'Transport Service'), ('rental', 'Car Rental'), ('passport', 'Passport Renewal'), ('protocol', 'Airport Protocol')], max_length=50),
        ),
    ]
