# Generated by Django 4.2.28 on 2026-03-03 10:58

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
