# Generated by Django 4.2.28 on 2026-03-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_alter_hotel_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='available_rooms',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='hotel',
            name='rooms',
            field=models.JSONField(blank=True, help_text='\n        Example:\n        [\n            {\n                "room_name": "Deluxe Room",\n                "price": 50000,\n                "currency": "NGN",\n                "refundable": true,\n                "highlights": ["Free WiFi", "Air conditioning"],\n                "photos": ["url1", "url2"]\n            }\n        ]\n        ', null=True),
        ),
    ]
