# Generated by Django 4.2.28 on 2026-03-04 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0004_hotel_available_rooms_hotel_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='booking_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='external_id',
            field=models.CharField(blank=True, help_text='Hotel ID from external API', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='source',
            field=models.CharField(choices=[('internal', 'Internal'), ('external', 'External')], default='internal', max_length=20),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='price_per_night',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='rooms',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
