# Generated by Django 4.2.28 on 2026-03-10 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0005_hotel_booking_url_hotel_external_id_hotel_source_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hotel",
            name="booking_url",
        ),
        migrations.RemoveField(
            model_name="hotel",
            name="external_id",
        ),
        migrations.RemoveField(
            model_name="hotel",
            name="source",
        ),
    ]
