# Generated by Django 4.2.28 on 2026-03-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotels", "0006_remove_hotel_external_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotelreservation",
            name="hold_expires_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
