# Generated by Django 4.2.28 on 2026-03-16 13:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(max_length=10)),
                ('target_currency', models.CharField(max_length=10)),
                ('rate', models.DecimalField(decimal_places=6, max_digits=12)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('resource_type', models.CharField(choices=[('flight', 'Flight'), ('hotel', 'Hotel'), ('transport', 'Transport'), ('visa', 'Visa')], max_length=50)),
                ('rule_type', models.CharField(choices=[('percentage', 'Percentage'), ('flat', 'Flat Fee')], max_length=20)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('country', models.CharField(blank=True, max_length=10, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
