# Generated by Django 4.2.28 on 2026-02-28 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('flights', '0001_initial'),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisaApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_country', models.CharField(max_length=100)),
                ('visa_type', models.CharField(max_length=100)),
                ('appointment_date', models.DateField(blank=True, null=True)),
                ('document_status', models.CharField(default='pending', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending submission'), ('verified', 'Documents verified'), ('submitted', 'Submitted to embassy'), ('approved', 'Approved by embassy'), ('rejected', 'Rejected by embassy')], default='pending', max_length=20)),
                ('passport_scan', models.FileField(blank=True, null=True, upload_to='visa_documents/passports/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='visa_documents/photos/')),
                ('supporting_docs', models.FileField(blank=True, null=True, upload_to='visa_documents/supporting/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookings.booking')),
                ('flight', models.ForeignKey(blank=True, help_text='Linked flight booking (required for visa application)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='flights.flightbooking')),
            ],
        ),
    ]
