# Generated by Django 4.2.28 on 2026-03-18 13:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("visas", "0002_alter_visaapplication_flight"),
    ]

    operations = [
        migrations.DeleteModel(name="VisaApplication"),
        migrations.CreateModel(
            name="VisaApplication",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("visa_type", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("incomplete", "Incomplete"),
                            ("ready_for_payment", "Ready for payment"),
                            ("paid", "Paid"),
                            ("submitted", "Submitted"),
                            ("under_review", "Under review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("is_locked", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="visa_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VisaDocument",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("document_type", models.CharField(max_length=100)),
                ("file", models.FileField(upload_to="visa_documents/")),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="documents",
                        to="visas.visaapplication",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VisaPayment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("successful", "Successful"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=255, unique=True)),
                ("tx_ref", models.CharField(max_length=100)),
                ("payment_reference", models.CharField(blank=True, max_length=100)),
                ("payment_link", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="payments",
                        to="visas.visaapplication",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["tx_ref"], name="visas_visap_tx_ref_9a4a8a_idx"),
                    models.Index(fields=["status"], name="visas_visap_status_2c78a8_idx"),
                ]
            },
        ),
    ]
