# Generated by Django 4.2.28 on 2026-03-19 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visas', '0005_add_visa_type_model'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='visapayment',
            new_name='visas_visap_tx_ref_1d25d4_idx',
            old_name='visas_visap_tx_ref_9a4a8a_idx',
        ),
        migrations.RenameIndex(
            model_name='visapayment',
            new_name='visas_visap_status_166be8_idx',
            old_name='visas_visap_status_2c78a8_idx',
        ),
        migrations.RenameIndex(
            model_name='visatype',
            new_name='visas_visat_country_a6d719_idx',
            old_name='visas_visat_country_3b7f7d_idx',
        ),
    ]
