# Generated by Django 4.2.28 on 2026-03-19 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visas', '0006_add_visa_type_fields'),
        ('visas', '0006_rename_visas_visap_tx_ref_9a4a8a_idx_visas_visap_tx_ref_1d25d4_idx_and_more'),
    ]

    operations = [
    ]
