# Generated by Django 4.2.28 on 2026-02-28 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('van', 'Van'), ('bus', 'Bus'), ('luxury', 'Luxury Vehicle')], max_length=50)),
                ('transport_name', models.CharField(max_length=150)),
                ('pickup_location', models.CharField(max_length=200)),
                ('dropoff_location', models.CharField(max_length=200)),
                ('price_per_passenger', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('passengers', models.IntegerField(default=1)),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transport_details', to='bookings.booking')),
            ],
        ),
    ]
