# Generated by Django 4.2.28 on 2026-03-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportservice',
            name='vehicle_type',
            field=models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('van', 'Van'), ('bus', 'Bus'), ('luxury', 'Luxury Vehicle'), ('car_rental', 'Car Rental')], max_length=50),
        ),
    ]
