# Generated by Django 4.2.28 on 2026-03-20 02:52

import app.transport.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_service_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transport', '0003_transportreservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passengers', models.PositiveIntegerField(default=1)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.CharField(blank=True, max_length=150, null=True)),
                ('special_requests', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('checked_in', 'Checked In'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('reference', models.CharField(default=app.transport.models.generate_transport_reference, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('organization', models.CharField(blank=True, max_length=150, null=True)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('flight_number', models.CharField(blank=True, max_length=50, null=True)),
                ('airline', models.CharField(blank=True, max_length=100, null=True)),
                ('expected_arrival_time', models.DateTimeField(blank=True, null=True)),
                ('capacity', models.PositiveIntegerField()),
                ('booked_seats', models.PositiveIntegerField(default=0)),
                ('is_shared', models.BooleanField(default=True)),
                ('price_per_seat', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('assigned', 'Assigned'), ('en_route', 'En Route'), ('arrived', 'Arrived'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TripAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('active', 'Active'), ('completed', 'Completed')], default='assigned', max_length=20)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='transport.trip')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('sedan', 'Sedan'), ('suv', 'SUV'), ('van', 'Van'), ('bus', 'Bus'), ('luxury', 'Luxury')], max_length=50)),
                ('plate_number', models.CharField(max_length=50, unique=True)),
                ('capacity', models.PositiveIntegerField()),
                ('provider', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('maintenance', 'Maintenance')], default='available', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='transportservice',
            name='booking',
        ),
        migrations.DeleteModel(
            name='TransportReservation',
        ),
        migrations.DeleteModel(
            name='TransportService',
        ),
        migrations.AddField(
            model_name='tripassignment',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.vehicle'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['departure_time'], name='transport_t_departu_24ed42_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['status'], name='transport_t_status_17a22f_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['pickup_location'], name='transport_t_pickup__beb18e_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['dropoff_location'], name='transport_t_dropoff_00871d_idx'),
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.CheckConstraint(check=models.Q(('capacity__gte', 1)), name='trip_capacity_gte_1'),
        ),
        migrations.AddField(
            model_name='transportbooking',
            name='booking',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transport_booking', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='transportbooking',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='transport.trip'),
        ),
        migrations.AddField(
            model_name='transportbooking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='tripassignment',
            unique_together={('trip', 'vehicle')},
        ),
        migrations.AddIndex(
            model_name='transportbooking',
            index=models.Index(fields=['trip'], name='transport_t_trip_id_e05cd7_idx'),
        ),
        migrations.AddIndex(
            model_name='transportbooking',
            index=models.Index(fields=['user'], name='transport_t_user_id_bacea8_idx'),
        ),
        migrations.AddIndex(
            model_name='transportbooking',
            index=models.Index(fields=['status'], name='transport_t_status_f08964_idx'),
        ),
        migrations.AddIndex(
            model_name='transportbooking',
            index=models.Index(fields=['reference'], name='transport_t_referen_4e6741_idx'),
        ),
        migrations.AddConstraint(
            model_name='transportbooking',
            constraint=models.CheckConstraint(check=models.Q(('passengers__gte', 1)), name='transport_passengers_gte_1'),
        ),
        migrations.AlterUniqueTogether(
            name='transportbooking',
            unique_together={('trip', 'user')},
        ),
    ]
