# Generated by Django 4.2.28 on 2026-03-16 13:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=50)),
                ('resource_type', models.CharField(choices=[('flight', 'Flight'), ('hotel', 'Hotel'), ('transport', 'Transport')], max_length=50)),
                ('resource_id', models.CharField(max_length=255)),
                ('available_quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=10)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('last_synced', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('provider', 'resource_id')},
            },
        ),
    ]
