# Generated by Django 4.2.28 on 2026-03-20 02:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='inventory',
            name='dropoff_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='pickup_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inventory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='resource_id',
            field=models.UUIDField(),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='resource_type',
            field=models.CharField(choices=[('trip', 'Trip'), ('flight', 'Flight'), ('hotel', 'Hotel')], max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('provider', 'resource_id', 'start_time')},
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['resource_type'], name='inventory_i_resourc_ab13f1_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['start_time'], name='inventory_i_start_t_3da029_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['end_time'], name='inventory_i_end_tim_a09846_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['pickup_location'], name='inventory_i_pickup__39aedd_idx'),
        ),
        migrations.AddIndex(
            model_name='inventory',
            index=models.Index(fields=['dropoff_location'], name='inventory_i_dropoff_c465e6_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventory',
            constraint=models.CheckConstraint(check=models.Q(('available_quantity__gte', 0)), name='inventory_available_quantity_non_negative'),
        ),
    ]
