# Generated by Django 4.2.28 on 2026-03-20 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0004_alter_booking_service_type'),
        ('transport', '0004_transportbooking_trip_tripassignment_vehicle_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarRental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(blank=True, max_length=255, null=True)),
                ('deposit_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='car_rental', to='bookings.booking')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transport.vehicle')),
            ],
            options={
                'indexes': [models.Index(fields=['start_date'], name='rentals_car_start_d_8f0a56_idx'), models.Index(fields=['end_date'], name='rentals_car_end_dat_7740a4_idx'), models.Index(fields=['vehicle'], name='rentals_car_vehicle_db7ad1_idx'), models.Index(fields=['user'], name='rentals_car_user_id_b8824f_idx'), models.Index(fields=['status'], name='rentals_car_status_d09613_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='carrental',
            constraint=models.CheckConstraint(check=models.Q(('end_date__gt', models.F('start_date'))), name='rental_end_date_after_start_date'),
        ),
    ]
